'use strict';

const ActionTypes = {
    "ADD_GOAL": "ADD_GOAL",
    "ADD_GOAL_SUCCESS": "ADD_GOAL_SUCCESS",
    "ADD_GOAL_ERROR": "ADD_GOAL_ERROR",

    "GET_WEIGHT": "GET_WEIGHT",
    "GET_WEIGHT_SUCCESS": "GET_WEIGHT_SUCCESS",
    "GET_WEIGHT_ERROR": "GET_WEIGHT_ERROR",

    "ADD_WEIGHT": "ADD_WEIGHT",
    "ADD_WEIGHT_SUCCESS": "ADD_WEIGHT_SUCCESS",
    "ADD_WEIGHT_ERROR": "ADD_WEIGHT_ERROR",

    "DELETE_WEIGHT": "DELETE_WEIGHT",
    "DELETE_WEIGHT_SUCCESS": "DELETE_WEIGHT_SUCCESS",
    "DELETE_WEIGHT_ERROR": "DELETE_WEIGHT_ERROR",

    "GET_USER": "GET_USER",
    "GET_USER_SUCCESS": "GET_USER_SUCCESS",
    "GET_USER_ERROR": "GET_USER_ERROR",
}

export default ActionTypes;
